In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
ball = pd.read_csv("c:/Users/Danish/OneDrive/Desktop/infosys/Datasets/ball_by_ball_data.csv")
matches = pd.read_csv("c:/Users/Danish/OneDrive/Desktop/infosys/Datasets/ipl_matches_data.csv")
players = pd.read_csv("c:/Users/Danish/OneDrive/Desktop/infosys/Datasets/players-data-updated.csv")
team_alias = pd.read_csv("c:/Users/Danish/OneDrive/Desktop/infosys/Datasets/team_aliases.csv")
teams_data = pd.read_csv("c:/Users/Danish/OneDrive/Desktop/infosys/Datasets/teams_data.csv")

In [5]:
ball.head()

,season_id,match_id,batter,bowler,non_striker,team_batting,team_bowling,over_number,ball_number,batter_runs,...,is_bye,is_penalty,wide_ball_runs,no_ball_runs,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,6,1,0,0,0,...,False,False,0,0,1,0,0,NaN,False,1
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,1,0,...,False,False,0,0,0,0,0,NaN,False,1
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,2,0,...,False,False,1,0,0,0,0,NaN,False,1
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,3,0,...,False,False,0,0,0,0,0,NaN,False,1
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,6,1,0,4,0,...,False,False,0,0,0,0,0,NaN,False,1

In [6]:
matches.head()

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,venue,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,M Chinnaswamy Stadium,1,1,6,field,6,140.0,NaN,46.0,win
1,1082591,2017,6,Hyderabad,2017-04-05,Indian Premier League,1.0,male,T20,T20,...,"Rajiv Gandhi International Stadium, Uppal",1,2,1,field,2,35.0,NaN,15.0,win
2,1082592,2017,6,Pune,2017-04-06,Indian Premier League,2.0,male,T20,T20,...,Maharashtra Cricket Association Stadium,4,4,3,field,4,NaN,7.0,36.0,win
3,1082593,2017,6,Rajkot,2017-04-07,Indian Premier League,3.0,male,T20,T20,...,Saurashtra Cricket Association Stadium,6,5,6,field,6,NaN,10.0,57.0,win
4,1082594,2017,6,Indore,2017-04-08,Indian Premier League,4.0,male,T20,T20,...,Holkar Cricket Stadium,494,494,4,field,494,NaN,6.0,71.0,win

In [7]:
ball.shape

(278205, 30)

In [8]:
matches.shape

(1169, 23)

In [9]:
players.shape

(772, 6)

In [10]:
team_alias.shape

(46, 3)

In [11]:
teams_data.shape

(16, 2)

In [12]:
ball.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 30 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   season_id          278205 non-null  int64
 1   match_id           278205 non-null  int64
 2   batter             278205 non-null  object
 3   bowler             278205 non-null  object
 4   non_striker        278205 non-null  object
 5   team_batting       278205 non-null  int64
 6   team_bowling       278205 non-null  int64
 7   over_number        278205 non-null  int64
 8   ball_number        278205 non-null  int64
 9   batter_runs        278205 non-null  int64
 10  extras             278205 non-null  int64
 11  total_runs         278205 non-null  int64
 12  batsman_type       278205 non-null  object
 13  bowler_type        278205 non-null  object
 14  player_out         13823 non-null   object
 15  fielders_involved  13823 non-null   object
 16  is_wicket          278205 non-null  bool
 17  is_wide_ball       278205 non-null  bool
 18  is_no_ball         278205 non-null  bool
 19  is_leg_bye         278205 non-null  bool
 20  is_bye             278205 non-null  bool
 21  is_penalty         278205 non-null  bool
 22  wide_ball_runs     278205 non-null  int64
 23  no_ball_runs       278205 non-null  int64
 24  leg_bye_runs       278205 non-null  int64
 25  bye_runs           278205 non-null  int64
 26  penalty_runs       278205 non-null  int64
 27  wicket_kind        13823 non-null   object
 28  is_super_over      278205 non-null  bool
 29  innings            278205 non-null  int64
dtypes: bool(7), int64(15), object(8)
memory usage: 50.7+ MB

In [13]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_id         1169 non-null   int64
 1   season_id        1169 non-null   int64
 2   balls_per_over   1169 non-null   int64
 3   city             1118 non-null   object
 4   match_date       1169 non-null   object
 5   event_name       1169 non-null   object
 6   match_number     1099 non-null   float64
 7   gender           1169 non-null   object
 8   match_type       1169 non-null   object
 9   format           1169 non-null   object
 10  overs            1169 non-null   int64
 11  season           1169 non-null   object
 12  team_type        1169 non-null   object
 13  venue            1169 non-null   object
 14  toss_winner      1169 non-null   int64
 15  team1            1169 non-null   int64
 16  team2            1169 non-null   int64
 17  toss_decision    1169 non-null   object
 18  match_winner     1169 non-null   int64
 19  win_by_runs      531 non-null    float64
 20  win_by_wickets   615 non-null    float64
 21  player_of_match  1161 non-null   float64
 22  result           1169 non-null   object
dtypes: float64(4), int64(8), object(11)
memory usage: 210.2+ KB

In [14]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 772 entries, 0 to 771
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         772 non-null    int64
 1   player_name       772 non-null    object
 2   bat_style         772 non-null    object
 3   bowl_style        759 non-null    object
 4   field_pos         707 non-null    object
 5   player_full_name  772 non-null    object
dtypes: int64(1), object(5)
memory usage: 36.3+ KB

In [15]:
team_alias.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   alias_id    46 non-null     int64
 1   team_id     46 non-null     int64
 2   alias_name  46 non-null     object
dtypes: int64(2), object(1)
memory usage: 1.2+ KB

In [16]:
teams_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   team_id    16 non-null     int64
 1   team_name  16 non-null     object
dtypes: int64(1), object(1)
memory usage: 388.0+ bytes

In [17]:
team_alias.head(), teams_data.head()

(   alias_id  team_id                   alias_name
 0         1        1                          RCB
 1         2        1  Royal Challengers Bengaluru
 2         3      252             Delhi Daredevils
 3         4      494              Kings XI Punjab
 4         5        1  Royal Challengers Bangalore,
    team_id                    team_name
 0        1  Royal Challengers Bangalore
 1        2          Sunrisers Hyderabad
 2        3               Mumbai Indians
 3        4       Rising Pune Supergiant
 4        5                Gujarat Lions)

In [18]:
ball.describe

<bound method NDFrame.describe of         season_id  match_id        batter          bowler   non_striker  \
0            2008    335982    SC Ganguly         P Kumar   BB McCullum
1            2008    335982   BB McCullum         P Kumar    SC Ganguly
2            2008    335982   BB McCullum         P Kumar    SC Ganguly
3            2008    335982   BB McCullum         P Kumar    SC Ganguly
4            2008    335982   BB McCullum         P Kumar    SC Ganguly
...           ...       ...           ...             ...           ...
278200       2025   1485779      T Stubbs  Arshdeep Singh  Sameer Rizvi
278201       2025   1485779  Sameer Rizvi      MP Stoinis      T Stubbs
278202       2025   1485779  Sameer Rizvi      MP Stoinis      T Stubbs
278203       2025   1485779      T Stubbs      MP Stoinis  Sameer Rizvi
278204       2025   1485779  Sameer Rizvi      MP Stoinis      T Stubbs

        team_batting  team_bowling  over_number  ball_number  batter_runs  \
0                  6             1            0            0            0
1                  6             1            0            1            0
2                  6             1            0            2            0
3                  6             1            0            3            0
4                  6             1            0            4            0
...              ...           ...          ...          ...          ...
278200           252           494           18            5            4
278201           252           494           19            0            0
278202           252           494           19            1            1
278203           252           494           19            2            1
278204           252           494           19            3            6

        ...  is_bye  is_penalty wide_ball_runs no_ball_runs leg_bye_runs  \
0       ...   False       False              0            0            1
1       ...   False       False              0            0            0
2       ...   False       False              1            0            0
3       ...   False       False              0            0            0
4       ...   False       False              0            0            0
...     ...     ...         ...            ...          ...          ...
278200  ...   False       False              0            0            0
278201  ...   False       False              1            0            0
278202  ...   False       False              0            0            0
278203  ...   False       False              0            0            0
278204  ...   False       False              0            0            0

       bye_runs  penalty_runs  wicket_kind  is_super_over  innings
0             0             0          NaN          False        1
1             0             0          NaN          False        1
2             0             0          NaN          False        1
3             0             0          NaN          False        1
4             0             0          NaN          False        1
...         ...           ...          ...            ...      ...
278200        0             0          NaN          False        2
278201        0             0          NaN          False        2
278202        0             0          NaN          False        2
278203        0             0          NaN          False        2
278204        0             0          NaN          False        2

[278205 rows x 30 columns]>

In [19]:
def check_duplicates(df, name):
    dup_count = df.duplicated().sum()
    if dup_count == 0:
        print(f" {name}: No duplicate rows found")
    else:
        print(f" {name}: {dup_count} duplicate rows found")
    return dup_count

In [20]:
check_duplicates(ball, "Ball-by-Ball Data")
check_duplicates(matches, "Matches Data")
check_duplicates(players, "Players Data")
check_duplicates(team_alias, "Team Aliases Data")
check_duplicates(teams_data, "Teams Data")

 Ball-by-Ball Data: No duplicate rows found
 Matches Data: No duplicate rows found
 Players Data: No duplicate rows found
 Team Aliases Data: No duplicate rows found
 Teams Data: No duplicate rows found

np.int64(0)

In [21]:
team_id_map = dict(zip(teams_data['team_id'], teams_data['team_name']))
team_alias_map = dict(zip(team_alias['alias_id'], team_alias['alias_name']))

In [22]:
def map_team_name(value):

    if value in team_id_map:
        return team_id_map[value]

    if value in team_alias_map:
        return team_alias_map[value]
    
    return value

In [23]:
team_columns_matches = ['team1', 'team2', 'toss_winner', 'winner']

for col in team_columns_matches:
    if col in matches.columns:
        matches[col] = matches[col].apply(map_team_name)

In [24]:
team_columns_ball = ['batting_team', 'bowling_team']

for col in team_columns_ball:
    if col in ball.columns:
        ball[col] = ball[col].apply(map_team_name)

In [25]:
matches['team1'].unique()

array(['Royal Challengers Bangalore', 'Sunrisers Hyderabad',
       'Rising Pune Supergiant', 'Gujarat Lions', 'Punjab Kings',
       'Mumbai Indians', 'Kolkata Knight Riders', 'Delhi Capitals',
       'Rajasthan Royals', 'Chennai Super Kings', 'Lucknow Super Giants',
       'Gujarat Titans', 'Kochi Tuskers Kerala', 'Pune Warriors'],
      dtype=object)

In [26]:
def null_report(df, name):
    
    print(f"\n===== {name} =====")
    total_rows = df.shape[0]
    
    null_count = df.isnull().sum()
    null_percent = (null_count / total_rows) * 100
    
    report = pd.DataFrame({
        "Null_Count": null_count,
        "Null_Percent": null_percent
    }).sort_values(by="Null_Percent", ascending=False)
    
    report = report[report["Null_Count"] > 0]
    
    if report.empty:
        print("No null values found ")
    else:
        print(report)

In [27]:
null_report(ball, "Ball By Ball Data")
null_report(matches, "Matches Data")

===== Ball By Ball Data =====
                   Null_Count  Null_Percent
fielders_involved      264382     95.031362
player_out             264382     95.031362
wicket_kind            264382     95.031362

===== Matches Data =====
                 Null_Count  Null_Percent
win_by_runs             638     54.576561
win_by_wickets          554     47.390932
match_number             70      5.988024
city                     51      4.362703
player_of_match           8      0.684346

In [28]:
matches['win_by_runs'] = matches['win_by_runs'].fillna(0)
matches['win_by_wickets'] = matches['win_by_wickets'].fillna(0)

matches['match_number'] = matches['match_number'].fillna('No Result')
matches['player_of_match'] = matches['player_of_match'].fillna('Not Awarded')
matches['city'] = matches['city'].fillna('Unknown')

In [29]:
team_cols = ['team1', 'team2', 'toss_winner', 'match_winner']
for col in team_cols:
    matches[col] = matches[col].fillna('Unknown')

    matches[col] = matches[col].replace('', 'Unknown')

matches.reset_index(drop=True, inplace=True)

In [30]:
null_report(matches, "Matches Data")

===== Matches Data =====
No null values found

In [31]:
ball.drop(columns=['fielders_involved'], inplace=True, errors='ignore')

ball['player_out'] = ball['player_out'].fillna('Not Out')
ball['wicket_kind'] = ball['wicket_kind'].fillna('None')

numeric_cols_ball = ['total_runs', 'batter_runs', 'extras', 'over_number', 'ball_number']
for col in numeric_cols_ball:
    if col in ball.columns:
        ball[col] = ball[col].fillna(0)

ball.reset_index(drop=True, inplace=True)

In [32]:
null_report(ball, "Ball By Ball Data")

===== Ball By Ball Data =====
No null values found

In [33]:
ball.dtypes

season_id          int64
match_id           int64
batter            object
bowler            object
non_striker       object
team_batting       int64
team_bowling       int64
over_number        int64
ball_number        int64
batter_runs        int64
extras             int64
total_runs         int64
batsman_type      object
bowler_type       object
player_out        object
is_wicket           bool
is_wide_ball        bool
is_no_ball          bool
is_leg_bye          bool
is_bye              bool
is_penalty          bool
wide_ball_runs     int64
no_ball_runs       int64
leg_bye_runs       int64
bye_runs           int64
penalty_runs       int64
wicket_kind       object
is_super_over       bool
innings            int64
dtype: object

In [34]:
numeric_cols_ball = [
    'season_id', 'match_id', 'team_batting', 'team_bowling',
    'over_number', 'ball_number', 'batter_runs', 'extras',
    'total_runs', 'wide_ball_runs', 'no_ball_runs', 
    'leg_bye_runs', 'bye_runs', 'innings'
]
for col in numeric_cols_ball:
    if col in ball.columns:
        ball[col] = ball[col].fillna(0)

bool_cols_ball = ['is_wicket', 'is_wide_ball', 'is_no_ball', 'is_leg_bye', 'is_bye', 'is_super_over']
for col in bool_cols_ball:
    if col in ball.columns:
        ball[col] = ball[col].fillna(False)

In [35]:
null_report(ball, "Ball By Ball Data")
null_report(matches, "Matches Data")
null_report(players, "Players Data")
null_report(team_alias, "Team Aliases")
null_report(teams_data, "Teams Data")

===== Ball By Ball Data =====
No null values found

===== Matches Data =====
No null values found

===== Players Data =====
            Null_Count  Null_Percent
field_pos           65      8.419689
bowl_style          13      1.683938

===== Team Aliases =====
No null values found

===== Teams Data =====
No null values found

In [36]:
players['field_pos'] = players['field_pos'].fillna('Unknown')
players['bowl_style'] = players['bowl_style'].fillna('Unknown')

In [37]:
null_report(players, "Players Data")

===== Players Data =====
No null values found

In [38]:
ball_drop_cols = [
    'batsman_type',
    'bowler_type',
    'fielders_involved',
    'is_penalty',
    'penalty_runs'
]

ball.drop(columns=ball_drop_cols, inplace=True, errors='ignore')

In [39]:
matches_drop_cols = [
    'balls_per_over',
    'gender',
    'team_type',
    'format',
    'event_name',
    'season'
]

matches.drop(columns=matches_drop_cols, inplace=True, errors='ignore')

In [40]:
print("Ball columns:", ball.shape)
print("Matches columns:", matches.shape)

Ball columns: (278205, 25)
Matches columns: (1169, 17)

In [41]:
ball['is_super_over'].value_counts()

is_super_over
False    278034
True        171
Name: count, dtype: int64

In [42]:
team_id_to_name = dict(
    zip(teams_data['team_id'], teams_data['team_name'])
)

team_id_to_name

{1: 'Royal Challengers Bangalore',
 2: 'Sunrisers Hyderabad',
 3: 'Mumbai Indians',
 4: 'Rising Pune Supergiant',
 5: 'Gujarat Lions',
 6: 'Kolkata Knight Riders',
 129: 'Chennai Super Kings',
 134: 'Rajasthan Royals',
 252: 'Delhi Capitals',
 494: 'Punjab Kings',
 614: 'Lucknow Super Giants',
 615: 'Gujarat Titans',
 1068: 'Deccan Chargers',
 1414: 'Kochi Tuskers Kerala',
 1419: 'Pune Warriors',
 3604: 'Rising Pune Supergiants'}

In [43]:
ball['team_batting'] = ball['team_batting'].map(team_id_to_name)
ball['team_bowling'] = ball['team_bowling'].map(team_id_to_name)

In [44]:
team_cols = ['team1', 'team2', 'toss_winner', 'match_winner']

for col in team_cols:
    matches[col] = matches[col].map(team_id_to_name)

In [45]:
team_cols_fill = ['team1', 'team2', 'toss_winner']
for col in team_cols_fill:
    matches[col] = matches[col].fillna('Unknown')

In [46]:
matches.shape

(1169, 17)

In [47]:
matches.isnull().sum()

match_id           0
season_id          0
city               0
match_date         0
match_number       0
match_type         0
overs              0
venue              0
toss_winner        0
team1              0
team2              0
toss_decision      0
match_winner       0
win_by_runs        0
win_by_wickets     0
player_of_match    0
result             0
dtype: int64

In [48]:
(ball['total_runs'] >= ball['batter_runs']).all()

np.True_

In [49]:
ball[['batter_runs','extras','total_runs']].describe()

         batter_runs         extras    total_runs
count  278205.000000  278205.000000  278205.00000
mean        1.277378       0.067971       1.34535
std         1.651107       0.343033       1.63762
min         0.000000       0.000000       0.00000
25%         0.000000       0.000000       0.00000
50%         1.000000       0.000000       1.00000
75%         1.000000       0.000000       1.00000
max         6.000000       7.000000       7.00000

In [50]:
null_report(ball, "Ball By Ball Data")
null_report(matches, "Matches Data")
null_report(players, "Players Data")
null_report(team_alias, "Team Aliases")
null_report(teams_data, "Teams Data")

===== Ball By Ball Data =====
No null values found

===== Matches Data =====
No null values found

===== Players Data =====
No null values found

===== Team Aliases =====
No null values found

===== Teams Data =====
No null values found

In [58]:
players.replace(r'^\s*$', pd.NA, regex=True, inplace=True)

In [64]:
categorical_cols = players.select_dtypes(include="object").columns

players[categorical_cols] = players[categorical_cols].fillna("Unknown")

In [70]:
numeric_cols = players.select_dtypes(include=["int64", "float64"]).columns

players[numeric_cols] = players[numeric_cols].fillna(0)

In [76]:
players.isnull().sum()

player_id           0
player_name         0
bat_style           0
bowl_style          0
field_pos           0
player_full_name    0
dtype: int64

In [77]:
ball.shape

(278205, 25)

In [78]:
matches.shape

(1169, 17)

In [79]:
matches.head()

,match_id,season_id,city,match_date,match_number,match_type,overs,venue,toss_winner,team1,team2,toss_decision,match_winner,win_by_runs,win_by_wickets,player_of_match,result
0,335982,2008,Bangalore,2008-04-18,1.0,T20,20,M Chinnaswamy Stadium,Unknown,Unknown,Unknown,field,Kolkata Knight Riders,140.0,0.0,46.0,win
1,1082591,2017,Hyderabad,2017-04-05,1.0,T20,20,"Rajiv Gandhi International Stadium, Uppal",Unknown,Unknown,Unknown,field,Sunrisers Hyderabad,35.0,0.0,15.0,win
2,1082592,2017,Pune,2017-04-06,2.0,T20,20,Maharashtra Cricket Association Stadium,Unknown,Unknown,Unknown,field,Rising Pune Supergiant,0.0,7.0,36.0,win
3,1082593,2017,Rajkot,2017-04-07,3.0,T20,20,Saurashtra Cricket Association Stadium,Unknown,Unknown,Unknown,field,Kolkata Knight Riders,0.0,10.0,57.0,win
4,1082594,2017,Indore,2017-04-08,4.0,T20,20,Holkar Cricket Stadium,Unknown,Unknown,Unknown,field,Punjab Kings,0.0,6.0,71.0,win

In [98]:
print("Ball:", ball.shape)
print("Matches:", matches.shape)
print("Players:", players.shape)

Ball: (278205, 25)
Matches: (1169, 17)
Players: (772, 6)

In [ ]:
import os

cleaned_path = "c:/Users/Danish/OneDrive/Desktop/infosys/Datasets/cleaned"
os.makedirs(cleaned_path, exist_ok=True)

In [111]:
cleaned_path = "Datasets/cleaned"

balls = pd.read_csv(f"{cleaned_path}/ball_cleaned.csv")
matches = pd.read_csv(f"{cleaned_path}/matches_cleaned.csv")
players = pd.read_csv(f"{cleaned_path}/player_cleaned.csv")
team_alias = pd.read_csv(f"{cleaned_path}/team_aliases_cleaned.csv")
teams = pd.read_csv(f"{cleaned_path}/teams_data_cleaned.csv")