In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
batsman = pd.read_csv("/content/batsman_match_final_stage2.csv")
bowler = pd.read_csv("/content/bowler_match_final_stage2.csv")

print(" Dataset loaded successfully")
print("➡ Shape:", batsman.shape)
print("➡ Columns:",(batsman.columns))

print("➡ Shape:", bowler.shape)
print("➡ Columns:",(bowler.columns))

 Dataset loaded successfully
➡ Shape: (11680, 23)
➡ Columns: Index(['matchid', 'date', 'season', 'venue', 'city', 'batting_team',
       'bowling_team', 'batsman', 'runs', 'balls_faced', 'fours', 'sixes',
       'strike_rate', 'avg_runs_last_5', 'avg_runs_last_10',
       'avg_runs_at_venue', 'matches_at_venue', 'matches_played',
       'career_avg_runs', 'career_avg_balls', 'boundary_rate',
       'recent_form_indicator', 'experience_level'],
      dtype='object')
➡ Shape: (9283, 25)
➡ Columns: Index(['matchid', 'date', 'season', 'venue', 'city', 'bowling_team',
       'batting_team', 'bowler', 'runs_conceded', 'balls_bowled', 'wicket',
       'wides', 'no_balls', 'overs', 'economy', 'avg_wkts_last_5',
       'avg_wkts_last_10', 'avg_wkts_at_venue', 'matches_at_venue',
       'matches_played', 'career_avg_wickets', 'career_avg_runs_conceded',
       'career_avg_overs', 'discipline_score', 'recent_vs_career_form'],
      dtype='object')

In [2]:
batsman.dtypes

matchid                    int64
date                      object
season                    object
venue                     object
city                      object
batting_team              object
bowling_team              object
batsman                   object
runs                       int64
balls_faced                int64
fours                      int64
sixes                      int64
strike_rate              float64
avg_runs_last_5          float64
avg_runs_last_10         float64
avg_runs_at_venue        float64
matches_at_venue           int64
matches_played             int64
career_avg_runs          float64
career_avg_balls         float64
boundary_rate            float64
recent_form_indicator      int64
experience_level          object
dtype: object

In [3]:
bowler.dtypes

matchid                       int64
date                         object
season                       object
venue                        object
city                         object
bowling_team                 object
batting_team                 object
bowler                       object
runs_conceded                 int64
balls_bowled                  int64
wicket                        int64
wides                         int64
no_balls                      int64
overs                       float64
economy                     float64
avg_wkts_last_5             float64
avg_wkts_last_10            float64
avg_wkts_at_venue           float64
matches_at_venue              int64
matches_played                int64
career_avg_wickets          float64
career_avg_runs_conceded    float64
career_avg_overs            float64
discipline_score            float64
recent_vs_career_form         int64
dtype: object

In [4]:
batsman.isna().sum()

matchid                  0
date                     0
season                   0
venue                    0
city                     0
batting_team             0
bowling_team             0
batsman                  0
runs                     0
balls_faced              0
fours                    0
sixes                    0
strike_rate              0
avg_runs_last_5          0
avg_runs_last_10         0
avg_runs_at_venue        0
matches_at_venue         0
matches_played           0
career_avg_runs          0
career_avg_balls         0
boundary_rate            0
recent_form_indicator    0
experience_level         0
dtype: int64

**Encoding the Experience level column**

In [5]:
exp_map = {
    "new": 0,
    "experienced": 1,
    "veteran": 2
}

batsman["experience_level_enc"] = batsman["experience_level"].map(exp_map)
batsman.drop(columns=["experience_level"], inplace=True)

In [6]:
print("# --- Identify Object Columns --- #")
print("# ---------------------------------#")
print("\n")
batsman_object_cols = batsman.select_dtypes(include=['object']).columns.tolist()
bowler_object_cols = bowler.select_dtypes(include=['object']).columns.tolist()

print("Batsman dataset object columns:")
print(batsman_object_cols)

print("\nBowler dataset object columns:")
print(bowler_object_cols)

# --- Identify Object Columns --- #
# ---------------------------------#


Batsman dataset object columns:
['date', 'season', 'venue', 'city', 'batting_team', 'bowling_team', 'batsman']

Bowler dataset object columns:
['date', 'season', 'venue', 'city', 'bowling_team', 'batting_team', 'bowler']

In [7]:
print(batsman['venue'].unique())

['Wankhede Stadium' 'MA Chidambaram Stadium, Chepauk'
 'Rajiv Gandhi International Stadium, Uppal' 'M Chinnaswamy Stadium'
 'Feroz Shah Kotla' 'Eden Gardens'
 'Maharashtra Cricket Association Stadium' 'Sawai Mansingh Stadium'
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium'
 'Punjab Cricket Association Stadium, Mohali' 'Newlands'
 "St George's Park" 'Kingsmead' 'New Wanderers Stadium'
 'Vidarbha Cricket Association Stadium, Jamtha'
 'Dr DY Patil Sports Academy' 'SuperSport Park' 'Barabati Stadium'
 'Brabourne Stadium' 'Nehru Stadium' 'Sardar Patel Stadium, Motera'
 'M.Chinnaswamy Stadium'
 'Punjab Cricket Association IS Bindra Stadium, Mohali' 'Green Park'
 'Arun Jaitley Stadium' 'MA Chidambaram Stadium'
 'Himachal Pradesh Cricket Association Stadium'
 'JSCA International Stadium Complex' 'OUTsurance Oval'
 'Sheikh Zayed Stadium' 'De Beers Diamond Oval' 'Holkar Cricket Stadium'
 'Subrata Roy Sahara Stadium' 'Buffalo Park'
 'Saurashtra Cricket Association Stadium'
 'Shaheed Veer Narayan Singh International Stadium'
 'Rajiv Gandhi International Stadium'
 'Punjab Cricket Association IS Bindra Stadium'
 'MA Chidambaram Stadium, Chepauk, Chennai' 'Wankhede Stadium, Mumbai'
 'Brabourne Stadium, Mumbai']

In [8]:
print(bowler['venue'].unique())

['Subrata Roy Sahara Stadium' 'Wankhede Stadium' 'Barabati Stadium'
 'MA Chidambaram Stadium, Chepauk' 'M Chinnaswamy Stadium'
 'Rajiv Gandhi International Stadium, Uppal' 'Eden Gardens'
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium'
 'Sawai Mansingh Stadium' 'Punjab Cricket Association Stadium, Mohali'
 'Newlands' "St George's Park" 'Kingsmead' 'New Wanderers Stadium'
 'SuperSport Park' 'Brabourne Stadium' 'Feroz Shah Kotla'
 'Vidarbha Cricket Association Stadium, Jamtha'
 'Dr DY Patil Sports Academy' 'Buffalo Park' 'OUTsurance Oval'
 'Sardar Patel Stadium, Motera' 'Nehru Stadium'
 'Himachal Pradesh Cricket Association Stadium'
 'Maharashtra Cricket Association Stadium' 'Sheikh Zayed Stadium'
 'Shaheed Veer Narayan Singh International Stadium'
 'Saurashtra Cricket Association Stadium'
 'Punjab Cricket Association IS Bindra Stadium, Mohali'
 'M.Chinnaswamy Stadium' 'Green Park'
 'Punjab Cricket Association IS Bindra Stadium' 'Arun Jaitley Stadium'
 'Rajiv Gandhi International Stadium' 'MA Chidambaram Stadium'
 'Wankhede Stadium, Mumbai' 'MA Chidambaram Stadium, Chepauk, Chennai'
 'JSCA International Stadium Complex' 'De Beers Diamond Oval'
 'Holkar Cricket Stadium' 'Brabourne Stadium, Mumbai']

In [9]:
venue_to_state = {
    # Maharashtra
    "Wankhede Stadium": "Maharashtra",
    "Vidarbha Cricket Association Stadium, Jamtha": "Maharashtra",
    "Wankhede Stadium, Mumbai": "Maharashtra",
    "Brabourne Stadium": "Maharashtra",
    "Brabourne Stadium, Mumbai": "Maharashtra",
    "Dr DY Patil Sports Academy": "Maharashtra",
    "Maharashtra Cricket Association Stadium": "Maharashtra",
    "Subrata Roy Sahara Stadium": "Maharashtra",

    # Tamil Nadu
    "MA Chidambaram Stadium": "Tamil Nadu",
    "MA Chidambaram Stadium, Chepauk": "Tamil Nadu",
    "MA Chidambaram Stadium, Chepauk, Chennai": "Tamil Nadu",

    # Karnataka
    "M Chinnaswamy Stadium": "Karnataka",
    "M.Chinnaswamy Stadium": "Karnataka",

    # Delhi
    "Feroz Shah Kotla": "Delhi",
    "Arun Jaitley Stadium": "Delhi",

    # West Bengal
    "Eden Gardens": "West Bengal",

    # Telangana
    "Rajiv Gandhi International Stadium": "Telangana",
    "Rajiv Gandhi International Stadium, Uppal": "Telangana",

    # Rajasthan
    "Sawai Mansingh Stadium": "Rajasthan",

    # Gujarat
    "Sardar Patel Stadium, Motera": "Gujarat",
    "Saurashtra Cricket Association Stadium": "Gujarat",


    # Punjab
    "Punjab Cricket Association Stadium, Mohali": "Punjab",
    "Punjab Cricket Association IS Bindra Stadium": "Punjab",
    "Punjab Cricket Association IS Bindra Stadium, Mohali": "Punjab",

    # Madhya Pradesh
    "Holkar Cricket Stadium": "Madhya Pradesh",

    # Uttar Pradesh
    "Green Park": "Uttar Pradesh",

    # Jharkhand
    "JSCA International Stadium Complex": "Jharkhand",

    # Chhattisgarh
    "Shaheed Veer Narayan Singh International Stadium": "Chhattisgarh",

    # Himachal Pradesh
    "Himachal Pradesh Cricket Association Stadium": "Himachal Pradesh",

    # Andhra Pradesh
    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "Andhra Pradesh",

    # Odisha
    "Barabati Stadium": "Odisha",

    "Nehru Stadium": "Kerala",


    # Overseas
    "Newlands": "South Africa",
    "St George's Park": "South Africa",
    "Kingsmead": "South Africa",
    "New Wanderers Stadium": "South Africa",
    "SuperSport Park": "South Africa",
    "OUTsurance Oval": "South Africa",
    "De Beers Diamond Oval": "South Africa",
    "Buffalo Park": "South Africa",
    "Sheikh Zayed Stadium": "UAE"
}

In [10]:
batsman["venue_state"] = batsman["venue"].map(venue_to_state)

In [11]:
batsman[batsman["venue_state"].isna()]["venue"].unique()

array([], dtype=object)

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
batsman["venue_enc"] = le.fit_transform(batsman["venue_state"])
batsman.drop(columns=["venue_state","venue"], inplace=True)

In [13]:
venue_to_states = {

    # Maharashtra
    "Subrata Roy Sahara Stadium": "Maharashtra",
    "Wankhede Stadium": "Maharashtra",
    "Wankhede Stadium, Mumbai": "Maharashtra",
    "Brabourne Stadium": "Maharashtra",
    "Brabourne Stadium, Mumbai": "Maharashtra",
    "Dr DY Patil Sports Academy": "Maharashtra",
    "Maharashtra Cricket Association Stadium": "Maharashtra",
    "Vidarbha Cricket Association Stadium, Jamtha": "Maharashtra",

    # Tamil Nadu
    "MA Chidambaram Stadium": "Tamil Nadu",
    "MA Chidambaram Stadium, Chepauk": "Tamil Nadu",
    "MA Chidambaram Stadium, Chepauk, Chennai": "Tamil Nadu",

    # Karnataka
    "M Chinnaswamy Stadium": "Karnataka",
    "M.Chinnaswamy Stadium": "Karnataka",

    # Telangana
    "Rajiv Gandhi International Stadium": "Telangana",
    "Rajiv Gandhi International Stadium, Uppal": "Telangana",

    # West Bengal
    "Eden Gardens": "West Bengal",

    # Andhra Pradesh
    "Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium": "Andhra Pradesh",

    # Rajasthan
    "Sawai Mansingh Stadium": "Rajasthan",

    # Punjab
    "Punjab Cricket Association Stadium, Mohali": "Punjab",
    "Punjab Cricket Association IS Bindra Stadium": "Punjab",
    "Punjab Cricket Association IS Bindra Stadium, Mohali": "Punjab",

    # Delhi
    "Feroz Shah Kotla": "Delhi",
    "Arun Jaitley Stadium": "Delhi",

    # Odisha
    "Barabati Stadium": "Odisha",

    # Gujarat
    "Sardar Patel Stadium, Motera": "Gujarat",
    "Saurashtra Cricket Association Stadium": "Gujarat",

    # Kerala
    "Nehru Stadium": "Kerala",

    # Himachal Pradesh
    "Himachal Pradesh Cricket Association Stadium": "Himachal Pradesh",

    # Chhattisgarh
    "Shaheed Veer Narayan Singh International Stadium": "Chhattisgarh",

    # Jharkhand
    "JSCA International Stadium Complex": "Jharkhand",

    # Madhya Pradesh
    "Holkar Cricket Stadium": "Madhya Pradesh",

    # Uttar Pradesh
    "Green Park": "Uttar Pradesh",

    # UAE
    "Sheikh Zayed Stadium": "UAE",

    # South Africa
    "Newlands": "South Africa",
    "St George's Park": "South Africa",
    "Kingsmead": "South Africa",
    "New Wanderers Stadium": "South Africa",
    "SuperSport Park": "South Africa",
    "Buffalo Park": "South Africa",
    "OUTsurance Oval": "South Africa",
    "De Beers Diamond Oval": "South Africa"
}

In [14]:
bowler["venue_state"] = bowler["venue"].map(venue_to_states)

In [15]:
bowler[bowler["venue_state"].isna()]["venue"].unique()

array([], dtype=object)

In [16]:
bowler["venue_enc"] = le.fit_transform(bowler["venue_state"])
bowler.drop(columns=["venue_state","venue"], inplace=True)

In [17]:
city_freq = batsman["city"].value_counts(normalize=True)

batsman["city_enc"] = batsman["city"].map(city_freq)
batsman.drop(columns=["city"], inplace=True)


city_freq = bowler["city"].value_counts(normalize=True)

bowler["city_enc"] = bowler["city"].map(city_freq)
bowler.drop(columns=["city"], inplace=True)

In [18]:
batsman["season"] = batsman["season"].str.split("/").str[0].astype(int)
bowler["season"] = bowler["season"].str.split("/").str[0].astype(int)

In [19]:
batsman["date"] = pd.to_datetime(batsman["date"])
batsman["match_year"]  = batsman["date"].dt.year
batsman["match_month"] = batsman["date"].dt.month

bowler["date"] = pd.to_datetime(bowler["date"])
bowler["match_year"]  = bowler["date"].dt.year
bowler["match_month"] = bowler["date"].dt.month

In [20]:
# =========================
# SAVE BATSMAN CSV
# =========================
batsman.to_csv(
    "batsman_final.csv",
    index=False
)

# =========================
# SAVE BOWLER CSV
# =========================
bowler.to_csv(
    "bowler_final.csv",
    index=False
)

In [21]:
bat = pd.read_csv("/content/batsman_final.csv")
bal = pd.read_csv("/content/bowler_final.csv")

In [22]:
bat.sample(10)

,matchid,date,season,batting_team,bowling_team,batsman,runs,balls_faced,fours,sixes,...,matches_played,career_avg_runs,career_avg_balls,boundary_rate,recent_form_indicator,experience_level_enc,venue_enc,city_enc,match_year,match_month
4870,548312,2012-04-08,2012,Rajasthan Royals,Kolkata Knight Riders,KK Cooper,5,4,0,0,...,1,11.000000,3.000000,0.000000,0,0,12,0.058134,2012,4
5041,829739,2015-04-20,2015,Delhi Daredevils,Kolkata Knight Riders,KM Jadhav,12,9,1,1,...,31,13.645161,10.580645,0.222222,0,1,2,0.094692,2015,4
11213,980913,2016-04-15,2016,Kings XI Punjab,Delhi Daredevils,WP Saha,3,7,0,0,...,54,19.796296,14.962963,0.000000,1,2,2,0.094692,2016,4
2882,548335,2012-04-22,2012,Deccan Chargers,Kolkata Knight Riders,DW Steyn,7,3,0,1,...,15,4.000000,4.866667,0.333333,1,0,10,0.009075,2012,4
1173,1136620,2018-05-27,2018,Chennai Super Kings,Sunrisers Hyderabad,AT Rayudu,16,19,1,1,...,116,25.146552,18.982759,0.105263,1,2,9,0.143750,2018,5
9494,1082610,2017-04-18,2017,Gujarat Lions,Royal Challengers Bangalore,SK Raina,23,8,2,2,...,144,29.326389,21.062500,0.500000,0,2,3,0.011986,2017,4
2956,1082609,2017-04-17,2017,Kings XI Punjab,Sunrisers Hyderabad,EJG Morgan,13,17,0,1,...,42,19.309524,15.785714,0.058824,0,1,15,0.082106,2017,4
2903,1136583,2018-04-24,2018,Mumbai Indians,Sunrisers Hyderabad,E Lewis,5,9,1,0,...,5,28.400000,18.000000,0.111111,0,0,9,0.143750,2018,4
5829,1082638,2017-05-08,2017,Sunrisers Hyderabad,Mumbai Indians,MC Henriques,44,35,6,0,...,48,19.187500,14.916667,0.171429,1,1,15,0.082106,2017,5
839,598071,2013-05-22,2013,Rajasthan Royals,Sunrisers Hyderabad,AM Rahane,18,20,0,1,...,48,26.604167,22.687500,0.050000,1,1,2,0.094692,2013,5

In [23]:
bal.head()

,matchid,date,season,bowling_team,batting_team,bowler,runs_conceded,balls_bowled,wicket,wides,...,matches_played,career_avg_wickets,career_avg_runs_conceded,career_avg_overs,discipline_score,recent_vs_career_form,venue_enc,city_enc,match_year,match_month
0,548341,2012-04-26,2012,Deccan Chargers,Pune Warriors,A Ashish Reddy,32,24,2,0,...,0,0.000000,0.000000,0.000000,0.000000,0,9,0.048153,2012,4
1,548346,2012-04-29,2012,Deccan Chargers,Mumbai Indians,A Ashish Reddy,10,13,1,1,...,1,2.000000,32.000000,4.000000,0.076923,0,9,0.138641,2012,4
2,548348,2012-05-01,2012,Deccan Chargers,Pune Warriors,A Ashish Reddy,31,18,1,0,...,2,1.500000,21.000000,3.083333,0.055556,0,10,0.009264,2012,5
3,548352,2012-05-04,2012,Deccan Chargers,Chennai Super Kings,A Ashish Reddy,15,12,1,0,...,3,1.333333,24.333333,3.055556,0.083333,0,14,0.084563,2012,5
4,548356,2012-05-06,2012,Deccan Chargers,Royal Challengers Bangalore,A Ashish Reddy,35,24,1,1,...,4,1.250000,22.000000,2.791667,0.041667,0,6,0.079608,2012,5

In [24]:
bat.shape

(11680, 25)

In [25]:
bat.isna().sum()

matchid                  0
date                     0
season                   0
batting_team             0
bowling_team             0
batsman                  0
runs                     0
balls_faced              0
fours                    0
sixes                    0
strike_rate              0
avg_runs_last_5          0
avg_runs_last_10         0
avg_runs_at_venue        0
matches_at_venue         0
matches_played           0
career_avg_runs          0
career_avg_balls         0
boundary_rate            0
recent_form_indicator    0
experience_level_enc     0
venue_enc                0
city_enc                 0
match_year               0
match_month              0
dtype: int64