In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("merged_clean_ipl.csv", low_memory=False)

print("Initial Shape:", df.shape)
df.head()

Initial Shape: (57005, 76)

,unnamed:_0_x,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over_bat,ball,...,balls,fours,sixes,sr,unnamed:_0,over_bowl,maidens,runs_conceded,wickets,dots
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,131972,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
drop_cols = ["unnamed:_0_x", "unnamed:_0_y", "unnamed:_0"]
df = df.drop(columns=[c for c in drop_cols if c in df.columns])

print("Shape after dropping index cols:", df.shape)

Shape after dropping index cols: (57005, 73)

In [7]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")

df = df.sort_values(
    ["match_id", "innings", "over_bat", "ball"]
)

print("Missing dates:", df["date"].isna().sum())
df[["match_id", "date"]].head()

Missing dates: 0

   match_id       date
0    335982 2008-04-18
1    335982 2008-04-18
2    335982 2008-04-18
3    335982 2008-04-18
4    335982 2008-04-18

In [8]:
df["valid_ball"] = df["valid_ball"].fillna(0).astype(int)

df["valid_ball"].value_counts()

valid_ball
1    54862
0     2143
Name: count, dtype: int64

In [9]:
num_cols = [
    "runs_batter", "runs_bowler", "runs_extras",
    "runs_total", "bowler_wicket"
]

df[num_cols] = df[num_cols].fillna(0)

df[num_cols].isna().sum()

runs_batter      0
runs_bowler      0
runs_extras      0
runs_total       0
bowler_wicket    0
dtype: int64

In [10]:
df = df[df["match_type"] == "T20"]

print("After T20 filter:", df.shape)

After T20 filter: (57005, 73)

In [11]:
df.to_csv("preprocessed_ipl_ball_by_ball.csv", index=False)
print("Saved preprocessed_ipl_ball_by_ball.csv")

Saved preprocessed_ipl_ball_by_ball.csv